en:
  site.name: '«OGT»'
  nav.home: 'Home'
  nav.city: 'Ashgabat'
  page.latest_news: 'Latest news'
  page.more: 'More'
  page.search: 'Search'
  page.next: 'Next'
  page.prev: 'Previous'
  page.search_result: 'The search results found: :number articles'
  footer.copyright: '© OGT 2020. All rights reserved'
  speaker.participating: 'Participating session(s)'
  speaker.time: 'Time:'
  speaker.topic: 'Topic:'
  post.latest: 'Last news'
  sponsor.official: 'Official partners'
  sponsor.media: 'Media partners'
  sponsor.premier: 'Premier partners'
  sponsor.event: 'Event sponsors'
  sponsor.platinum: 'Platinum sponsors'
  sponsor.gold: 'Gold sponsors'
  sponsor.silver: 'Silver sponsors'
  sponsor.bronze: 'Bronze sponsors'
  contact.venue: 'Venue Info'
  contact.email: 'Email:'
  contact.site: 'Website:'
  contact.phone: 'Phone:'
  register: 'Registration'
ru:
  site.name: '«OGT»'
  nav.home: 'Главная'
  nav.city: 'Ашхабад'
  page.latest_news: 'Последние новости'
  page.more: 'Ещё'
  page.search: 'Поиск'
  page.next: 'Следующее'
  page.prev: 'Предыдущее'
  page.search_result: 'По результату поиска было найдено: :number статьи'
  footer.copyright: '© OGT 2020. Все права защищены'
  speaker.participating: 'Participating session(s)'
  speaker.time: 'Time:'
  speaker.topic: 'Topic:'
  post.latest: 'Last news'
  sponsor.official: 'Official partners'
  sponsor.media: 'Media partners'
  sponsor.premier: 'Premier partners'
  sponsor.event: 'Event sponsors'
  sponsor.platinum: 'Platinum sponsors'
  sponsor.gold: 'Gold sponsors'
  sponsor.silver: 'Silver sponsors'
  sponsor.bronze: 'Bronze sponsors'
  contact.venue: 'Информация о месте проведения'
  contact.email: 'Email:'
  contact.site: 'Веб-сайт:'
  contact.phone: 'Телефон:'
  register: 'Зарегистрироваться'

