en:
  site.name: '«OGT»'
  nav.home: 'Home'
  nav.city: 'Ashgabat'
  page.latest_news: 'Latest news'
  page.more: 'More'
  page.search: 'Search'
  page.next: 'Next'
  page.prev: 'Previous'
  page.search_result: 'The search results found: :number articles'
  footer.copyright: '© OGT 2020. All rights reserved'
  speaker.participating: 'Participating session(s)'
  speaker.time: 'Time:'
  speaker.topic: 'Topic:'
  post.latest: 'Last news'
  sponsor.official: 'Official partners'
  sponsor.media: 'Media partners'
  sponsor.premier: 'Premier partners'
  sponsor.event: 'Event sponsors'
  sponsor.platinum: 'Platinum sponsors'
  sponsor.gold: 'Gold sponsors'
  sponsor.silver: 'Silver sponsors'
  sponsor.bronze: 'Bronze sponsors'
  contact.venue: 'Venue Info'
  contact.email: 'Email:'
  contact.site: 'Website:'
  contact.phone: 'Phone:'
  event.about: 'Обзор мероприятия'
  event.about_conference: 'About conference'
  event.speakers: 'Speakers'
  event.sponsors: 'Partners & sponsors'
  event.program: 'Event program'
  event.venue: 'Venue'
  home.register: 'Registration'
  home.next_event: 'Next event'
  home.count_day: 'Day,Days'
  home.count_hour: 'Hour,Hours'
  home.count_min: 'Minute'
  home.count_sec: 'Second'
  home.online_conference: 'Live conference'
  home.about_event: 'About event'
  home.detail: 'Details'
  home.speakers: 'Speakers'
  home.all_speakers: 'All speakers'
  presentation.download: 'DOWNLOAD'
ru:
  site.name: '«OGT»'
  nav.home: 'Главная'
  nav.city: 'Ашхабад'
  page.latest_news: 'Последние новости'
  page.more: 'Ещё'
  page.search: 'Поиск'
  page.next: 'Следующее'
  page.prev: 'Предыдущее'
  page.search_result: 'По результату поиска было найдено: :number статьи'
  footer.copyright: '© OGT 2020. Все права защищены'
  speaker.participating: 'Participating session(s)'
  speaker.time: 'Time:'
  speaker.topic: 'Topic:'
  post.latest: 'Last news'
  sponsor.official: 'Official partners'
  sponsor.media: 'Media partners'
  sponsor.premier: 'Premier partners'
  sponsor.event: 'Event sponsors'
  sponsor.platinum: 'Platinum sponsors'
  sponsor.gold: 'Gold sponsors'
  sponsor.silver: 'Silver sponsors'
  sponsor.bronze: 'Bronze sponsors'
  contact.venue: 'Информация о месте проведения'
  contact.email: 'Email:'
  contact.site: 'Веб-сайт:'
  contact.phone: 'Телефон:'
  event.about: 'Обзор мероприятия'
  event.about_conference: 'О конференции'
  event.speakers: 'Спикеры'
  event.sponsors: 'Партнеры и спонсоры'
  event.program: 'Программа мероприятия'
  event.venue: 'Место проведения'

  home.register: 'Зарегистрироваться'
  home.next_event: 'Следующее мероприятие'
  home.count_day: 'Дeн,Дней'
  home.count_hour: 'Час,Часов'
  home.count_min: 'Минут'
  home.count_sec: 'Секунд'
  home.online_conference: 'Конференция в прямом эфире'
  home.about_event: 'О мероприятии'
  home.detail: 'Подробнее'
  home.speakers: 'Спикеры'
  home.all_speakers: 'Все спикеры'
  presentation.download: 'DOWNLOAD'

